# Generated by Django 4.2.5 on 2023-09-15 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 1, 17, 22, 291832)),
            preserve_default=False,
        ),
    ]
