# Generated by Django 4.2.5 on 2023-09-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_user_followers_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(related_name='likes', to='network.post'),
        ),
    ]
